services:
  nearp2p-swap:
    image: metademocracia1/nearp2p-swap:latest
    container_name: nearp2p-swap
    restart: always
    env_file: ".env.production"
    environment:
      - NODE_ENV=production
    volumes:
      - .env.production:/app/.env
    ports:
      - "3000:3000"
    networks:
      - proxy_net


  watchtower-walletp2p:
    image: containrrr/watchtower
    container_name: watchtower-walletp2p-latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
