services:
  walletp2p_backend:
    image: metademocracia1/walletp2p_backend:latest
    container_name: walletp2p_backend
    restart: always
    env_file: ".env"
    environment:
      - NODE_ENV=production
    volumes:
      - .env:/app/.env
    ports:
      - "3002:3002"
    networks:
      - proxy_net


  watchtower-walletp2p:
    image: containrrr/watchtower
    container_name: watchtower-walletp2p-latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
